name: "CI: MCP"

on:
  workflow_dispatch:

jobs:
  test-mcp:
    name: "Test MCP"
    runs-on: penpot-extended-runner
    container: penpotapp/devenv:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup
        working-directory: ./mcp
        run: ./scripts/setup

      - name: Check
        working-directory: ./mcp
        run: |
          pnpm run fmt:check;
          pnpm -r run build;
          pnpm -r run types:check;

      - name: Tests
        working-directory: ./mcp
        run: |
          pnpm run test;
